### ISSUE TITLE
Selection Texture mangled with IndexedBitmap

### ISSUE THREAD

**Issue by shadeops** [fabioarnold/MiniPixel#46]
Howdy!

I was playing with MiniPixel and noticed whenever I select part of the image while in Index mode, the selection texture gets mangled if the selection width is an odd number.

Here is an example gif that alternates between selections with an odd numbered width and an even numbered width.

![MiniPixel](https://user-images.githubusercontent.com/2104033/211266799-9a1967dd-5fe8-404d-908d-4b29a2bdaf5f.gif)

I traced through the code a bit to try to track this down but everything seems to be working fine until the IndexBitmap is passed to nanovg. For example, 
https://github.com/fabioarnold/MiniPixel/blob/cb255f193b9c8234847f5642f0c8b20a0e86a426/src/Document.zig#L1305
`selection.indexed_bitmap.indices` had the values that I would expect.

This behaviour shows up in Linux and in Windows. Tested on v0.2.1 and the current master, cb255f1.

I'm happy to continue to debug, but just wanted to flag the issue.

Thanks.

**Comment by fabioarnold** [comment]
Hey, thank you for your detailed bug report! This is awesome! 😄

Looks like the issue is that `GL_UNPACK_ALIGNMENT` defaults to `4` (see https://registry.khronos.org/OpenGL-Refpages/gl4/html/glPixelStore.xhtml). Calling `gl.glPixelStorei(gl.GL_UNPACK_ALIGNMENT, 1);` seems to fix the issue in https://github.com/fabioarnold/nanovg-zig/commit/731e4d079419718fdd1e71570fa23c2ab820b8f9.
