### ISSUE TITLE
Issues Minimizing Window on Linux

### ISSUE THREAD

**Issue by shadeops** [fabioarnold/MiniPixel#47]
Howdy,

I noticed some issues when trying to minimize MiniPixel on Linux. (MiniPixel is so awesome I hadn't tried to minimize it before now. :smile: )

Here is a .gif of what happens when the window's minimize button is clicked.

![MiniPixel](https://user-images.githubusercontent.com/2104033/211739861-96c9e83f-a5de-41b6-b08b-ce03087f09b6.gif)

The window loses focus but the immediately seems to un-minimize itself. Additionally if I go to another desktop, I can see it show up in the task bar which generally only happens if an application is trying to get attention.

I have zero SDL experience, but my _guess_ is that the `SdlWindow.draw()` call is sees that the window is hidden and tells the window manager to show it:
https://github.com/fabioarnold/MiniPixel/blob/f5f0195e40bb5e3545a8687817f6cb9c13fd6067/src/main.zig#L261-L263

I made a small change here, https://github.com/shadeops/MiniPixel/commit/9728a1abe6f0e1b2e04827bcbf2508a41966245b, which avoids the `SdlWindow.draw()` call entirely if minimized.

Note - This doesn't appear to be a problem with  0.2.1 on Windows.

OS: Kubuntu 20.04
Head: f5f0195e40bb5e3545a8687817f6cb9c13fd6067

**Comment by fabioarnold** [comment]
Oh, I never noticed because this issue doesn't show on Gnome:
[Screencast from 12.01.2023 22:10:15.webm](https://user-images.githubusercontent.com/473672/212181999-fe8f1dc8-5992-40fb-afa9-e1e3a98d5005.webm)

It's a bit annoying that KDE conflates the hidden and minimized state of windows. But I guess you can work around that by checking both flags as you did.

IIRC, I added this window unhide mechanism to avoid initially showing a black flash because nothing had been drawn, yet.

I'll try to reproduce this on my Steam Deck. I think it does have KDE. :smile:

**Comment by fabioarnold** [comment]
Check out Mini Pixel running on the Steam Deck! 😄 (Had to install Zig and VS Code first)
![A9510900-807A-4298-A19E-B26191166194_1_102_o](https://user-images.githubusercontent.com/473672/212192147-54f3de73-70ab-4f8e-a3c6-3c0cf4227e30.jpeg)

And yes I can reproduce your issue now! Do you mind opening a PR with your change, please?

**Comment by shadeops** [comment]
Yas! That is so amazing. And now I want a Steam Deck!
